package ru.lyrian.collections_operations_time.enumerations;

public enum ViewTag {
    TV_ARRAY_LIST_CREATE(FragmentTag.COLLECTIONS, OperationType.CREATION),
    PB_ARRAY_LIST_CREATE(FragmentTag.COLLECTIONS, OperationType.CREATION),
    TV_ARRAY_LIST_ADD_IN_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_ARRAY_LIST_ADD_IN_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_ARRAY_LIST_ADD_IN_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_ARRAY_LIST_ADD_IN_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_ARRAY_LIST_ADD_IN_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_ARRAY_LIST_ADD_IN_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_ARRAY_LIST_SEARCH_BY_VALUE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_ARRAY_LIST_SEARCH_BY_VALUE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_ARRAY_LIST_REMOVE_FROM_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_ARRAY_LIST_REMOVE_FROM_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_ARRAY_LIST_REMOVE_FROM_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_ARRAY_LIST_REMOVE_FROM_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_ARRAY_LIST_REMOVE_FROM_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_ARRAY_LIST_REMOVE_FROM_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_LINKED_LIST_CREATE(FragmentTag.COLLECTIONS, OperationType.CREATION),
    PB_LINKED_LIST_CREATE(FragmentTag.COLLECTIONS, OperationType.CREATION),
    TV_LINKED_LIST_ADD_IN_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_LINKED_LIST_ADD_IN_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_LINKED_LIST_ADD_IN_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_LINKED_LIST_ADD_IN_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_LINKED_LIST_ADD_IN_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_LINKED_LIST_ADD_IN_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_LINKED_LIST_SEARCH_BY_VALUE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_LINKED_LIST_SEARCH_BY_VALUE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_LINKED_LIST_REMOVE_FROM_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_LINKED_LIST_REMOVE_FROM_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_LINKED_LIST_REMOVE_FROM_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_LINKED_LIST_REMOVE_FROM_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_LINKED_LIST_REMOVE_FROM_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_LINKED_LIST_REMOVE_FROM_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_COPY_ON_WRITE_ARRAY_LIST_CREATE(FragmentTag.COLLECTIONS, OperationType.CREATION),
    PB_COPY_ON_WRITE_ARRAY_LIST_CREATE(FragmentTag.COLLECTIONS, OperationType.CREATION),
    TV_COPY_ON_WRITE_ARRAY_LIST_ADD_IN_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_COPY_ON_WRITE_ARRAY_LIST_ADD_IN_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_COPY_ON_WRITE_ARRAY_LIST_ADD_IN_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_COPY_ON_WRITE_ARRAY_LIST_ADD_IN_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_COPY_ON_WRITE_ARRAY_LIST_ADD_IN_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_COPY_ON_WRITE_ARRAY_LIST_ADD_IN_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_COPY_ON_WRITE_ARRAY_LIST_SEARCH_BY_VALUE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_COPY_ON_WRITE_ARRAY_LIST_SEARCH_BY_VALUE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_COPY_ON_WRITE_ARRAY_LIST_REMOVE_FROM_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_COPY_ON_WRITE_ARRAY_LIST_REMOVE_FROM_THE_BEGINNING(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_COPY_ON_WRITE_ARRAY_LIST_REMOVE_FROM_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_COPY_ON_WRITE_ARRAY_LIST_REMOVE_FROM_THE_MIDDLE(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_COPY_ON_WRITE_ARRAY_LIST_REMOVE_FROM_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    PB_COPY_ON_WRITE_ARRAY_LIST_REMOVE_FROM_THE_END(FragmentTag.COLLECTIONS, OperationType.MEASUREMENT),
    TV_HASH_MAP_CREATE(FragmentTag.MAPS, OperationType.CREATION),
    PB_HASH_MAP_CREATE(FragmentTag.MAPS, OperationType.CREATION),
    TV_HASH_MAP_ADD_NEW(FragmentTag.MAPS, OperationType.MEASUREMENT),
    PB_HASH_MAP_ADD_NEW(FragmentTag.MAPS, OperationType.MEASUREMENT),
    TV_HASH_MAP_SEARCH_BY_KEY(FragmentTag.MAPS, OperationType.MEASUREMENT),
    PB_HASH_MAP_SEARCH_BY_KEY(FragmentTag.MAPS, OperationType.MEASUREMENT),
    TV_HASH_MAP_REMOVING(FragmentTag.MAPS, OperationType.MEASUREMENT),
    PB_HASH_MAP_REMOVING(FragmentTag.MAPS, OperationType.MEASUREMENT),
    TV_TREE_MAP_CREATE(FragmentTag.MAPS, OperationType.CREATION),
    PB_TREE_MAP_CREATE(FragmentTag.MAPS, OperationType.CREATION),
    TV_TREE_MAP_ADD_NEW(FragmentTag.MAPS, OperationType.MEASUREMENT),
    PB_TREE_MAP_ADD_NEW(FragmentTag.MAPS, OperationType.MEASUREMENT),
    TV_TREE_MAP_SEARCH_BY_KEY(FragmentTag.MAPS, OperationType.MEASUREMENT),
    PB_TREE_MAP_SEARCH_BY_KEY(FragmentTag.MAPS, OperationType.MEASUREMENT),
    TV_TREE_MAP_REMOVING(FragmentTag.MAPS, OperationType.MEASUREMENT),
    PB_TREE_MAP_REMOVING(FragmentTag.MAPS, OperationType.MEASUREMENT);

    private FragmentTag fragmentTag;
    private OperationType operationType;

    ViewTag(FragmentTag fragmentTag, OperationType operationType) {
        this.fragmentTag = fragmentTag;
        this.operationType = operationType;
    }

    public FragmentTag getFragmentTag() {
        return fragmentTag;
    }

    public boolean isCreationOperation() {
        return this.operationType == OperationType.CREATION;
    }
}


